version: "3.6"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    command: npm start
    container_name: node
    ports:
      - "4200:4200"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    restart: unless-stopped
  coffee-shop:
    build:
      context: .
      dockerfile: Dockerfile-backend
    command: flask run -h "0.0.0.0" --reload
    container_name: coffee-shop
    env_file:
      - .env
    image: python:3.9.5
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./backend/src:/usr/src/app/
